import { colors } from '../styles';

export default {
  IMAGE_CROP_PICKER_OPTIONS: {
    width: 400,
    height: 400,
    cropping: true,
    includeBase64: true,
    freeStyleCropEnabled: true,
    cropperCircleOverlay: true,
    disableCropperColorSetters: true,
    useFrontCamera: true,
    showCropGuidelines: true,
    showCropFrame: true,
    hideBottomControls: true,
    enableRotationGesture: true,
    compressImageQuality: 0.8,
    mediaType: 'photo',
    cropperActiveWidgetColor: colors.redCrayola,
    cropperStatusBarColor: colors.redCrayola,
    cropperToolbarColor: colors.redCrayola,
    cropperToolbarWidgetColor: colors.redCrayola,
    cropperToolbarTitle: 'Sua foto de perfil',
  },
  FIXED_EXPENSE_TAGS: [
    'Luz',
    'Água',
    'Internet',
    'Despesa do mês',
    'Aluguel',
    'Mobilidade',
    'Almoço',
    'Feira',
    'Netflix',
    'Spotify',
    'Doação à UIPA',
    'Ração',
    'PSN',
  ],
  DEFAULT_EXPENSE_CATEGORIES: [
    { description: 'Moradia', icon: 'FontAwesome:home', color: '#f4a261' },
    {
      description: 'Contas Residenciais',
      icon: 'Ionicons:documents',
      color: '#2a9d8f',
    },
    {
      description: 'Saúde',
      icon: 'MaterialCommunityIcons:heart-pulse',
      color: '#606c38',
    },
    {
      description: 'Educação',
      icon: 'Octicons:mortar-board',
      color: '#457b9d',
    },
    {
      description: 'Transporte',
      icon: 'FontAwesome5:bus-alt',
      color: '#e3e3e3',
    },
    {
      description: 'Mercado',
      icon: 'MaterialIcons:local-grocery-store',
      color: '#1976d2',
    },
    {
      description: 'Cuidados Pessoais',
      icon: 'MaterialIcons:self-improvement',
      color: '#ef476f',
    },
    {
      description: 'Assinaturas & Serviços',
      icon: 'MaterialCommunityIcons:palette-swatch',
      color: '#161a1d',
    },
    {
      description: 'Lazer',
      icon: 'MaterialCommunityIcons:emoticon-happy',
      color: '#5a189a',
    },
    {
      description: 'Comida',
      icon: 'MaterialIcons:dinner-dining',
      color: '#e5383b',
    },
    {
      description: 'Presentes & Doações',
      icon: 'MaterialCommunityIcons:gift',
      color: '#ffc4d6',
    },
    { description: 'Família', icon: 'Ionicons:ios-people', color: '#083d77' },
    { description: 'Viagem', icon: 'Entypo:aircraft', color: '#ff8811' },
    {
      description: 'Outfit',
      icon: 'MaterialCommunityIcons:hanger',
      color: '#C5B400',
    },
    { description: 'Taxas', icon: 'MaterialIcons:payments', color: '#FF6233' },
  ],
  FIXED_INCOME_TAGS: [
    'Salário',
    'Bico',
    'Mesada',
    'Inquilino',
    'Propriedade',
    'Loja Virtual',
    'Empreendimento',
  ],
  DEFAULT_INCOME_CATEGORIES: [
    {
      description: 'Investimento',
      icon: 'Entypo:area-graph',
      color: '#343a40',
    },
    {
      description: 'Benefício',
      icon: 'FontAwesome5:hands-helping',
      color: '#40916c',
    },
    {
      description: 'Salário',
      icon: 'MaterialIcons:attach-money',
      color: '#80b918',
    },
    {
      description: 'Empréstimo',
      icon: 'FontAwesome5:handshake',
      color: '#98c1d9',
    },
  ],
};
